### ISSUE TITLE
Find a better way to implement xChips functionality

### ISSUE THREAD

**Issue by OppositeWolf770** [GitNether/paperback#27]
Currently, if you blueprint an xChips Joker, the blueprint trigger acts on the original Joker. This is due to how the xChips function is implemented.

**Comment by srockw** [comment]
The xChips function implementation is actually correct, but since you're manually evaluating a card you need to ensure that the card passed to it is the blueprint joker instead of the xChips joker, which can easily be achieved by passing `context.blueprint_card or card` instead of just `card` to it. You can see an example of it in #79 where `SMODS.eval_this` is called so that it shows two messages in quick succession rather than one

**Comment by OppositeWolf770** [comment]
Oh cool, I didn't know that. Thank you! I'll test that out and probably get this issue closed out.
